spring:
  application:
    name: flyway-demo
  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/flywaydemodb"
    password: "password"
    username: "postgres"
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    max-active: 15
    max-idle: 10
    max-wait: 8000
flyway:
  url: jdbc:postgresql://localhost:5432/flywaydemodb
  schemas: flywaydemodb
  user: "postgres"
  password: "password"
  locations: "classpath:db/migration"
logging:
  level:
    org:
      flywaydb: DEBUG